name: Next.js CI

on:
  push:
    paths:
      - ".github/workflows/main.yaml"
      - "packages/nextjs/**"
      - "package.json"
  pull_request:
    branches:
      - main
    paths:
      - "packages/nextjs/**"

env:
  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

jobs:
  ci:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-22.04]
        node: [lts/*]

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Install Vercel CLI
        run: npm install -g vercel@latest


      - name: Enable Corepack
        run: corepack enable

      - name: Setup node env
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies (Next.js)
        run: |
          yarn config set nodeLinker node-modules
          yarn install --no-immutable
        working-directory: ./packages/nextjs

      - name: Build Project
        run: vercel build --token=$VERCEL_TOKEN

      - name: Install scarb
        uses: software-mansion/setup-scarb@v1
        with:
          scarb-version: "2.8.4"
          scarb-lock: ./packages/snfoundry/contracts/Scarb.lock

      - name: Run Next.js Tests
        run: yarn test:nextjs

      - name: Deploy to Vercel
        env:
          VERCEL_ORG_ID: $VERCEL_ORG_ID
          VERCEL_PROJECT_ID: $VERCEL_PROJECT_ID
        run: vercel deploy --prebuilt --prod --token=$VERCEL_TOKEN